language: php

php:
  - 7.1
  - 7.2
  - 7.3

services: mongodb

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.2 ]]; then pecl install mongodb; fi
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit -c phpunit.xml.dist

matrix:
  allow_failures:
    - php: 7.3
