language: php

php:
  - 7.1
  - 7.2
  - 7.3

services: mongodb

before_install:
  - if [[ $(phpenv version-name) = "7.1" ]]; then pecl install mongodb; fi
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
