version: '3'

services:
  php:
    build: docker/php
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mongo:4.4
    command: mongod
    volumes:
      - db:/data/db

volumes:
  db:
    driver: local
